#!/usr/bin/env node

/**
 * Vercel build script
 * Conditionally blocks web access in production based on config
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Import the config (we need to read it as a module)
// Since this runs in Node.js, we'll read the file directly
const apiConfigPath = path.join(__dirname, '..', 'utils', 'apiConfig.js');
const apiConfigContent = fs.readFileSync(apiConfigPath, 'utf8');

// Extract BLOCK_WEB_IN_PRODUCTION value using regex
// This is a simple approach - we're looking for: export const BLOCK_WEB_IN_PRODUCTION = true/false;
const blockWebMatch = apiConfigContent.match(/export const BLOCK_WEB_IN_PRODUCTION = (true|false);/);
const BLOCK_WEB_IN_PRODUCTION = blockWebMatch ? blockWebMatch[1] === 'true' : false;

console.log(`Building for Vercel...`);
console.log(`BLOCK_WEB_IN_PRODUCTION: ${BLOCK_WEB_IN_PRODUCTION}`);

try {
  // Ensure assets/api exists (generated by generate-data.js)
  const assetsApiPath = path.join(__dirname, '..', 'assets', 'api');
  if (!fs.existsSync(assetsApiPath)) {
    console.warn('Warning: assets/api folder not found. Run "npm run generate:data" first.');
  }

  // Always run Expo export
  console.log('Running Expo export...');
  execSync('npx expo export -p web', { stdio: 'inherit' });

  // Verify assets/api is included in dist (Expo should include it automatically)
  const distAssetsApiPath = path.join(__dirname, '..', 'dist', 'assets', 'api');
  if (!fs.existsSync(distAssetsApiPath)) {
    console.warn('Warning: assets/api not found in dist. Copying manually...');
    // Copy assets/api to dist/assets/api if Expo didn't include it
    if (fs.existsSync(assetsApiPath)) {
      const { execSync } = require('child_process');
      execSync(`cp -r "${assetsApiPath}" "${path.join(__dirname, '..', 'dist', 'assets')}"`, { stdio: 'inherit' });
    }
  }

  // Verify exclusions
  const distDataPath = path.join(__dirname, '..', 'dist', 'data');
  const distImagesHdPath = path.join(__dirname, '..', 'dist', 'images-hd');
  if (fs.existsSync(distDataPath)) {
    console.warn('Warning: data folder found in dist - this should not be included!');
  }
  if (fs.existsSync(distImagesHdPath)) {
    console.warn('Warning: images-hd folder found in dist - this should not be included!');
  }

  // Conditionally copy download page
  if (BLOCK_WEB_IN_PRODUCTION) {
    console.log('Blocking web access - copying download page...');
    const downloadPagePath = path.join(__dirname, '..', 'vercel', 'index.html');
    const distIndexPath = path.join(__dirname, '..', 'dist', 'index.html');
    
    if (fs.existsSync(downloadPagePath)) {
      fs.copyFileSync(downloadPagePath, distIndexPath);
      console.log('Download page copied successfully');
    } else {
      console.warn(`Warning: Download page not found at ${downloadPagePath}`);
    }
  } else {
    console.log('Web access enabled - using Expo-generated index.html');
  }

  console.log('Build completed successfully!');
  console.log('✓ Only assets folder and app code are included');
  console.log('✓ data/ and images-hd/ folders are excluded');
} catch (error) {
  console.error('Build failed:', error.message);
  process.exit(1);
}

